{
    'name': "Hotel ERP",
    'version': "18.0.1.1",
    'depends': ['base', 'mail', 'sale', 'account', 'lunch', 'base_automation'],
    'license': "LGPL-3",
    'summary': """An Erp for Hotel Management""",
    'description': """For Hotel Management """,
    'author': "Cybrosys",
    'category': "Services",
    'website': "www.cybrosys.com",
    'maintainer': "Cybrosys Technology Pvt Ltd <info@cybrosys.com>",
    'sequence': 1,
    'data': ["security/groups.xml",
             'security/ir.model.access.csv',
             "data/ir_cron_data.xml",
             "data/mail_template_checkout.xml",
             "data/rooms_data.xml",
             "data/hotel_facility_data.xml",
             "data/food_category_data.xml",
             "wizard/accommodation_report_views.xml",
             "views/ir_sequence_data.xml",
             'views/rooms_views.xml',
             "views/facility_views.xml",
             "views/hotel_food_views.xml",
             "views/food_category_views.xml",
             "views/accomodation_views.xml",
             "views/hotel_guest_views.xml",
             "views/sale_order_lines_views.xml",
             "views/order_food_views.xml",
             "views/res_partner_views.xml",
             'views/hotel_management_menus.xml',
             "report/hotel_management_report.xml",
             "report/hotel_management_report_template.xml"
             ],
    'application': True,
    'installable': True

}
