{
    'name': "Hotel ERP",
    'version': "18.0.1.1",
    'depends': ['base', 'mail', 'sale', 'account', 'lunch', 'base_automation','website', 'website_payment', 'portal'],
    'license': "LGPL-3",
    'summary': """An Erp for Hotel Management""",
    'description': """For Hotel Management """,
    'author': "Cybrosys",
    'category': "Services",
    'website': "www.cybrosys.com",
    'maintainer': "Cybrosys Technology Pvt Ltd <info@cybrosys.com>",
    'sequence': 1,
    'data': ["security/groups.xml",
             'security/ir.model.access.csv',
             "data/ir_cron_data.xml",
             "data/mail_template_checkout.xml",
             "data/hotel_facility_data.xml",
             "data/rooms_data.xml",
             "data/food_category_data.xml",
             "data/product_demo.xml",
             "wizard/accommodation_report_views.xml",
             "views/ir_sequence_data.xml",
             'views/rooms_views.xml',
             "views/facility_views.xml",
             "views/hotel_food_views.xml",
             "views/food_category_views.xml",
             "views/hotel_gallery.xml",
             "views/accomodation_views.xml",
             "views/hotel_guest_views.xml",
             "views/sale_order_lines_views.xml",
             "views/order_food_views.xml",
             "views/res_partner_views.xml",
             'views/hotel_management_menus.xml',
             "website/snippet.xml",
             'website/hotel_booking_form.xml',
             'website/hotel_rooms_snippet.xml',
             'website/hotel_gallery_snippet.xml',
             "website/food_order_portal_templates.xml",
             "website/portal_food_list_template.xml",
             "website/portal_food_cart_template.xml",
             'website/website_menu.xml',
             "report/hotel_management_report.xml",
             "report/hotel_management_report_template.xml"
             ],
    'assets': {'web.assets_backend': ['hotel_management/static/src/js/action_manager.js'],
               'web.assets_frontend':["hotel_management/static/src/js/hotel_booking.js",
                                      "hotel_management/static/src/js/no_of_guest.js",
                                      "hotel_management/static/src/css/banner_snippet.css",
                                      "hotel_management/static/src/xml/hotel_room_template.xml",
                                      "hotel_management/static/src/js/hotel_room_snippet.js",
                                      "hotel_management/static/src/xml/hotel_gallery_template.xml",
                                      "hotel_management/static/src/js/hotel_gallery_snippet.js",
                                      ]},
    'application': True,
    'installable': True

}
