{
    'name': 'POS Product Brand',
    'version':"18.0.1.1",
    'license':"LGPL-3",
    'summary':"""POS""",
    'description':"""User-friendly PoS interface for shops and restaurants""",
    'depends': ['base','sale_management','point_of_sale'],
    'author':"Cybrosys",
    'category':"Point of Sale",
    'website':"www.cybrosys.com",
    'maintainer':"Cybrosys Technology Pvt Ltd <info@cybrosys.com>",
    'sequence':1,
    'data':["security/ir.model.access.csv",
            "views/product_views.xml"],
    'assets': {'point_of_sale._assets_pos': ["pos_product_brand/static/src/js/pos_orderline.js",
                                            "pos_product_brand/static/src/js/orderline.js",
                                            "pos_product_brand/static/src/xml/pos_brand_template.xml",
                                       ]},
    'application':True,
    # 'auto_install':True,
    'installable':True
}